SQuadro/Controllers/EmailSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SQuadro.Models;

namespace SQuadro.Controllers
{
    [Authorize]
    public class EmailSettingsController : Controller
    {
        public EmailSettingsController(IListTemplate IListTemplate, IUsersHelper IUsersHelper)
        {
            this.IListTemplate = IListTemplate;
            this.IUsersHelper = IUsersHelper;
        }

        private IListTemplate IListTemplate;
        private IUsersHelper IUsersHelper;
        private EntityContext context = EntityContext.Current;

        public ActionResult Index()
        {
            ViewBag.ActiveInterfaceGroup = MainMenu.SettingsGroup;
            ViewBag.ActiveInterfaceItem = MainMenu.EmailSettings;

            IListTemplate.ParentID = IUsersHelper.CurrentUser.OrganizationID;
            IListTemplate.Initialize();
            return PartialView("ListTemplateView", IListTemplate);
        }

        [HttpPost]
        public ActionResult DataSourceCallback(DataTablesParam param, Guid parentID)
        {
            IListTemplate.ParentID = IUsersHelper.CurrentUser.OrganizationID;
            IListTemplate.Initialize();
            int totalRecords, filteredRecords;
            var result = IListTemplate.GetDataSource(param, Request, out totalRecords, out filteredRecords);

            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = filteredRecords,
                aaData = result
            });
        }

        [HttpPost]
        public ActionResult GetEmailSettingsDetails(Guid? id)
        {
            bool result = false;
            string description = String.Empty;
            string content = String.Empty;

            try
            {
                var model = EmailSettingsService.GetViewModel(id, IUsersHelper.CurrentUser.OrganizationID, context);
                content = this.PartialViewToString("Details", model);
                result = true;
            }
            catch (Exception e)
            {
                description = e.GetMessage();
            }
            return Json(new { Result = result, Description = description, Content = content });
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SetEmailSettingsDetails(EmailSettingsModel model)
        {
            bool result = false;

            try
            {
                if (ModelState.IsValid)
                {
                    EmailSettingsService.SetEmailSettings(model, context);
                    context.SaveChanges();
                    result = true;
                }
                else
                {
                    ModelState.AddModelError("", "Please correct all errors.");
                }
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.GetMessage());
            }
            string content = String.Empty;
            if (!result) content = this.PartialViewToString("Details", model);
            return Json(new { Result = result, Content = content });
        }

        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            bool result = false;
            string description = String.Empty;
            try
            {
                EmailSettingsService.DeleteEmailSettings(id, context);
                context.SaveChanges();
                result = true;
            }
            catch (Exception e)
            {
                description = e.GetMessage();
            }
            return Json(new { Result = result, Description = description });
        }

        [HttpPost]
        public ActionResult GetList(string term)
        {
            return Json(ListsHelper.EmailSettings(IUsersHelper.CurrentUser.OrganizationID).Where(
                e => String.IsNullOrEmpty(term) || e.Name.ToLower().Contains(term.ToLower()) || e.Email.ToLower().Contains(term.ToLower())).Select(
                    e => new Select2ListItem() { id = e.ID.ToString(), text = "{0} ({1})".ToFormat(e.Name, e.Email) }));
        }

        [HttpPost]
        public ActionResult GetSelectedItems(string selection)
        {
            var result = new List<object>() { new { id = Guid.Empty, text = String.Empty } };
            result.Clear();

            Guid tmpID = Guid.Empty;

            foreach (var id in selection.Split(',').Where(item => Guid.TryParse(item, out tmpID)).Select(item => tmpID))
            {

                EmailSettings emailSettings = EntityContext.Current.EmailSettings.SingleOrDefault(e => e.ID == id);
                if (emailSettings != null)
                    result.Add(new { id = emailSettings.ID.ToString(), text = "{0} ({1})".ToFormat(emailSettings.Name, emailSettings.Email) });
                else
                    result.Add(new { id = id.ToString(), text = "EmailSettings with ID {0} does not exist anymore".ToFormat(id) });
            }
            return Json(result);
        }
    }
}

SQuadro/Views/EmailSettings/Details.cshtml
@using SQuadro.Models;
@model EmailSettingsModel
@{
    Layout = null;
}
@using (Html.BeginForm("SetEmailSettingsDetails", "EmailSettings", FormMethod.Post, new { @class = "form-horizontal", id = "formDetail" }))
{
    @Html.HiddenFor(m => m.ID)
    @Html.HiddenFor(m => m.OrganizationID)
    @Html.ValidationSummary(true)
    <div class="form-group">
        @Html.LabelFor(m => m.Name, new { @class = "control-label col-lg-3", @for = "inputName" })
        <div class="col-lg-9">
            @Html.TextBoxFor(m => m.Name, new { id = "inputName", @class = "form-control", placeholder = "Input new Name" })
            @Html.ValidationMessageFor(m => m.Name)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "control-label col-lg-3", @for = "inputEmail" })
        <div class="col-lg-9">
            @Html.TextBoxFor(m => m.Email, new { id = "inputEmail", @class = "form-control", placeholder = "Input new Email Address" })
            @Html.ValidationMessageFor(m => m.Email)
        </div>
    </div>    
    <div class="form-group">
        <div class="col-lg-offset-3 col-lg-9">
            <label class="checkbox-container">
                @Html.HiddenFor(m => m.IsDefault, new { @class = "checkbox-value" })
                <input type="checkbox" checked="@Model.IsDefault" onchange="$(this).closest('.checkbox-container').find('.checkbox-value').val(this.checked)"/> Default
            </label>
            @Html.ValidationMessageFor(m => m.IsDefault)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SmtpServer, new { @class = "control-label col-lg-3", @for = "inputSmtpServer" })
        <div class="col-lg-9">
            @Html.TextBoxFor(m => m.SmtpServer, new { id = "inputSmtpServer", @class = "form-control", placeholder = "Input Smtp Server name" })
            @Html.ValidationMessageFor(m => m.SmtpServer)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SmtpPort, new { @class = "control-label col-lg-3", @for = "inputSmtpPort" })
        <div class="col-lg-9">
            @Html.TextBoxFor(m => m.SmtpPort, new { id = "inputSmtpPort", @class = "form-control", placeholder = "Input Smtp Port number" })
            @Html.ValidationMessageFor(m => m.SmtpPort)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SmtpUser, new { @class = "control-label col-lg-3", @for = "inputSmtpUser" })
        <div class="col-lg-9">
            @Html.TextBoxFor(m => m.SmtpUser, new { id = "inputSmtpUser", @class = "form-control", placeholder = "Input Smtp User name" })
            @Html.ValidationMessageFor(m => m.SmtpUser)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SmtpPassword, new { @class = "control-label col-lg-3", @for = "inputSmtpPassword" })
        <div class="col-lg-9">
            @Html.PasswordFor(m => m.SmtpPassword, new { id = "inputSmtpPassword", @class = "form-control", placeholder = "Input Smtp Password" })
            @Html.ValidationMessageFor(m => m.SmtpPassword)
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-3 col-lg-9">
            <label class="checkbox-container">
                @Html.HiddenFor(m => m.EnableSsl, new { @class = "checkbox-value" })
                <input type="checkbox" checked="@Model.IsDefault" onchange="$(this).closest('.checkbox-container').find('.checkbox-value').val(this.checked)"/> Enable Ssl
            </label>
            @Html.ValidationMessageFor(m => m.EnableSsl)
        </div>
    </div>
}